### ISSUE TITLE
请问vue的单文件是如何运行的

### ISSUE THREAD

**Issue by MuttonYung** [521xueweihan/OneFile#5]
你好，我现在正在学习vue，写过一些简单的项目，对这个开源项目也很感兴趣，但对vue底层原理不太了解，
我尝试替换vue项目中默认的index.html似乎并不能正常运行，打开网页是空白的，报了一些错误
![image](https://user-images.githubusercontent.com/55025557/209671150-95bc7b8b-f253-4dc1-88a3-994c0f514f2c.png)
该如何运行这个文件呢？

**Comment by 521xueweihan** [comment]
@MuttonYung 上图是静态资源加载失败的告警
